## Modelling

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

df10 = pd.read_csv('preprocess_merged_data_path10.csv')
df1028 = pd.read_csv('preprocess_merged_data_path1028.csv')
df28 = pd.read_csv('preprocess_merged_data_path28.csv')

In [2]:
df10.isnull().any()

date (yyyy-MM-dd HH:mm:ss)    False
windAlg.Spd_2m_kt             False
windAlg.Dir_2m                False
windAlg.SpdX_2m_kt            False
ALgt_1m_cd/m2                 False
windAlg.Spd_10m_kt            False
windAlg.Dir_10m               False
windAlg.DirCCw_10m            False
windAlg.DirCw_10m             False
windAlg.Peak_10m_kt           False
zenoAlg.AT_5m_C               False
zenoAlg.DP_5m_C               False
zenoAlg.RH_5m                 False
baroAlg.QNH_1m_mb             False
baroAlg.QFE_1m_mb             False
baroAlg.BPLow_1m_mb           False
visiAlg.F_Vis_1m_m            False
visiAlg.F_Vis_10m_m           False
visiAlg.VisMn_10m_m           False
visiAlg.VisMx_10m_m           False
touchdown.message             False
rollout.message               False
touchdown.edge                False
touchdown.center              False
ceilAlg.Base_30s_ft           False
ceilAlg.layer1_report         False
ceilAlg.layer2_report         False
ceilAlg.layer3_report         False
ceilAlg.layer4_report         False
visiAlg.PW_METAR              False
dtype: bool

In [3]:
# Kolom yang ingin Anda pertahankan
columns_to_keep = ['zenoAlg.AT_5m_C', 'zenoAlg.DP_5m_C', 'zenoAlg.RH_5m' , 'windAlg.Spd_2m_kt', 'windAlg.Dir_2m', 'ALgt_1m_cd/m2',
                  'baroAlg.QNH_1m_mb', 'baroAlg.QFE_1m_mb']

# Menjatuhkan semua kolom kecuali yang ingin dipertahankan
df_clasification_10 = df10.drop(columns=df10.columns.difference(columns_to_keep))
df_clasification_1028 = df1028.drop(columns=df1028.columns.difference(columns_to_keep))
df_clasification_28 = df28.drop(columns=df28.columns.difference(columns_to_keep))

# Tampilkan hasilnya
print(df_clasification_10, df_clasification_1028, df_clasification_28)

        windAlg.Spd_2m_kt  windAlg.Dir_2m  ALgt_1m_cd/m2  zenoAlg.AT_5m_C  \
0                     1.7           222.0         3704.0             26.4
1                     1.8           229.0         3743.0             26.4
2                     2.0           224.0         3906.0             26.4
3                     1.9           211.0         3990.0             26.4
4                     1.9           226.0         4087.0             26.5
...                   ...             ...            ...              ...
129595                3.9           296.0         4328.0             25.5
129596                4.4           303.0         4314.0             25.6
129597                4.2           307.0         4277.0             25.7
129598                4.4           304.0         4208.0             25.8
129599                4.7           304.0         4119.0             25.8

        zenoAlg.DP_5m_C  zenoAlg.RH_5m  baroAlg.QNH_1m_mb  baroAlg.QFE_1m_mb
0                  25.6           95.6             1008.1             1007.9
1                  25.6           95.4             1008.1             1008.0
2                  25.6           95.2             1008.1             1008.0
3                  25.7           95.1             1008.1             1008.0
4                  25.7           95.2             1008.1             1007.9
...                 ...            ...                ...                ...
129595             25.5           99.9             1010.5             1010.1
129596             25.5           99.7             1010.5             1010.2
129597             25.5           99.4             1010.5             1010.2
129598             25.6           99.2             1010.5             1010.2
129599             25.6           98.8             1010.5             1010.2

[129600 rows x 8 columns]         windAlg.Spd_2m_kt  windAlg.Dir_2m  zenoAlg.AT_5m_C  zenoAlg.DP_5m_C  \
0                     2.2           223.0             26.6             24.8
1                     1.7           214.0             26.6             24.9
2                     1.6           229.0             26.7             24.9
3                     1.7           236.0             26.8             24.9
4                     1.6           239.0             26.8             24.9
...                   ...             ...              ...              ...
129595                4.6           310.0             25.8             23.3
129596                4.9           303.0             25.8             23.3
129597                4.9           294.0             26.0             23.3
129598                4.7           308.0             26.1             23.3
129599                4.6           313.0             26.1             23.3

        zenoAlg.RH_5m  baroAlg.QNH_1m_mb  baroAlg.QFE_1m_mb
0                89.7             1008.1             1007.9
1                89.6             1008.1             1007.9
2                89.5             1008.1             1008.0
3                89.2             1008.1             1007.9
4                88.8             1008.1             1007.9
...               ...                ...                ...
129595           85.3             1010.5             1010.1
129596           85.3             1010.5             1010.2
129597           85.1             1010.5             1010.2
129598           84.9             1010.5             1010.2
129599           84.7             1010.5             1010.2

[129600 rows x 7 columns]         windAlg.Spd_2m_kt  windAlg.Dir_2m  ALgt_1m_cd/m2  zenoAlg.AT_5m_C  \
0                     2.1           192.0         4141.0             26.3
1                     2.0           194.0         4452.0             26.4
2                     1.8           184.0         4453.0             26.4
3                     1.1           194.0         4470.0             26.5
4                     0.6           210.0         4565.0             26.6
...                   ...             ...            ...              ...
129595                4.7           302.0         3910.0             25.6
129596                4.8           297.0         4061.0             25.6
129597                5.4           293.0         4300.0             25.7
129598                5.4           294.0         4357.0             25.8
129599                5.0           296.0         4493.0             25.8

        zenoAlg.DP_5m_C  zenoAlg.RH_5m  baroAlg.QNH_1m_mb  baroAlg.QFE_1m_mb
0                  25.7           96.4             1008.1             1007.8
1                  25.8           96.6             1008.1             1007.8
2                  25.9           96.6             1008.1             1007.8
3                  26.0           96.7             1008.1             1007.8
4                  26.0           96.6             1008.1             1007.8
...                 ...            ...                ...                ...
129595             25.6          100.0             1010.2             1010.0
129596             25.6          100.0             1010.5             1010.0
129597             25.7          100.0             1010.5             1010.0
129598             25.8          100.0             1010.5             1010.0
129599             25.9          100.0             1010.5             1010.1

[129600 rows x 8 columns]

In [4]:
df_clasification_10.rename(columns={'zenoAlg.AT_5m_C' : 'AT_10', 'zenoAlg.DP_5m_C' : 'dp_10', 'zenoAlg.RH_5m' : 'rh_10', 'windAlg.Spd_2m_kt' : 'spdWind_10', 
                                    'windAlg.Dir_2m': 'dirWind_10', 'ALgt_1m_cd/m2': 'cd_10' , 'baroAlg.QNH_1m_mb' : 'QNH_10', 'baroAlg.QFE_1m_mb': 'QFE_10'}, inplace=True)
df_clasification_1028.rename(columns={'zenoAlg.AT_5m_C' : 'AT_1028', 'zenoAlg.DP_5m_C' : 'dp_1028', 'zenoAlg.RH_5m' : 'rh_1028', 'windAlg.Spd_2m_kt' : 'spdWind_1028', 
                                    'windAlg.Dir_2m': 'dirWind_1028', 'ALgt_1m_cd/m2': 'cd_1028' , 'baroAlg.QNH_1m_mb' : 'QNH_1028', 'baroAlg.QFE_1m_mb': 'QFE_1028'}, inplace=True)
df_clasification_28.rename(columns={'zenoAlg.AT_5m_C' : 'AT_28', 'zenoAlg.DP_5m_C' : 'dp_28', 'zenoAlg.RH_5m' : 'rh_28', 'windAlg.Spd_2m_kt' : 'spdWind_28', 
                                    'windAlg.Dir_2m': 'dirWind_28', 'ALgt_1m_cd/m2': 'cd_28' , 'baroAlg.QNH_1m_mb' : 'QNH_28', 'baroAlg.QFE_1m_mb': 'QFE_28'}, inplace=True)

In [5]:
print(df_clasification_10, df_clasification_1028, df_clasification_28)

        spdWind_10  dirWind_10   cd_10  AT_10  dp_10  rh_10  QNH_10  QFE_10
0              1.7       222.0  3704.0   26.4   25.6   95.6  1008.1  1007.9
1              1.8       229.0  3743.0   26.4   25.6   95.4  1008.1  1008.0
2              2.0       224.0  3906.0   26.4   25.6   95.2  1008.1  1008.0
3              1.9       211.0  3990.0   26.4   25.7   95.1  1008.1  1008.0
4              1.9       226.0  4087.0   26.5   25.7   95.2  1008.1  1007.9
...            ...         ...     ...    ...    ...    ...     ...     ...
129595         3.9       296.0  4328.0   25.5   25.5   99.9  1010.5  1010.1
129596         4.4       303.0  4314.0   25.6   25.5   99.7  1010.5  1010.2
129597         4.2       307.0  4277.0   25.7   25.5   99.4  1010.5  1010.2
129598         4.4       304.0  4208.0   25.8   25.6   99.2  1010.5  1010.2
129599         4.7       304.0  4119.0   25.8   25.6   98.8  1010.5  1010.2

[129600 rows x 8 columns]         spdWind_1028  dirWind_1028  AT_1028  dp_1028  rh_1028  QNH_1028  \
0                2.2         223.0     26.6     24.8     89.7    1008.1
1                1.7         214.0     26.6     24.9     89.6    1008.1
2                1.6         229.0     26.7     24.9     89.5    1008.1
3                1.7         236.0     26.8     24.9     89.2    1008.1
4                1.6         239.0     26.8     24.9     88.8    1008.1
...              ...           ...      ...      ...      ...       ...
129595           4.6         310.0     25.8     23.3     85.3    1010.5
129596           4.9         303.0     25.8     23.3     85.3    1010.5
129597           4.9         294.0     26.0     23.3     85.1    1010.5
129598           4.7         308.0     26.1     23.3     84.9    1010.5
129599           4.6         313.0     26.1     23.3     84.7    1010.5

        QFE_1028
0         1007.9
1         1007.9
2         1008.0
3         1007.9
4         1007.9
...          ...
129595    1010.1
129596    1010.2
129597    1010.2
129598    1010.2
129599    1010.2

[129600 rows x 7 columns]         spdWind_28  dirWind_28   cd_28  AT_28  dp_28  rh_28  QNH_28  QFE_28
0              2.1       192.0  4141.0   26.3   25.7   96.4  1008.1  1007.8
1              2.0       194.0  4452.0   26.4   25.8   96.6  1008.1  1007.8
2              1.8       184.0  4453.0   26.4   25.9   96.6  1008.1  1007.8
3              1.1       194.0  4470.0   26.5   26.0   96.7  1008.1  1007.8
4              0.6       210.0  4565.0   26.6   26.0   96.6  1008.1  1007.8
...            ...         ...     ...    ...    ...    ...     ...     ...
129595         4.7       302.0  3910.0   25.6   25.6  100.0  1010.2  1010.0
129596         4.8       297.0  4061.0   25.6   25.6  100.0  1010.5  1010.0
129597         5.4       293.0  4300.0   25.7   25.7  100.0  1010.5  1010.0
129598         5.4       294.0  4357.0   25.8   25.8  100.0  1010.5  1010.0
129599         5.0       296.0  4493.0   25.8   25.9  100.0  1010.5  1010.1

[129600 rows x 8 columns]

In [6]:
# Menggabungkan dua file secara horizontal (kolom demi kolom)
merged_data = pd.concat([df_clasification_10, df_clasification_1028, df_clasification_28], axis=1)

# Menyimpan hasil gabungan ke file CSV baru
merged_data.to_csv('merged_df_clasification.csv', index=False)

In [7]:
df_cls = pd.read_csv('merged_df_clasification.csv')

In [8]:
df_cls.shape

(129600, 23)

In [9]:
df_cls.head()

,spdWind_10,dirWind_10,cd_10,AT_10,dp_10,rh_10,QNH_10,QFE_10,spdWind_1028,dirWind_1028,...,QNH_1028,QFE_1028,spdWind_28,dirWind_28,cd_28,AT_28,dp_28,rh_28,QNH_28,QFE_28
0,1.7,222.0,3704.0,26.4,25.6,95.6,1008.1,1007.9,2.2,223.0,...,1008.1,1007.9,2.1,192.0,4141.0,26.3,25.7,96.4,1008.1,1007.8
1,1.8,229.0,3743.0,26.4,25.6,95.4,1008.1,1008.0,1.7,214.0,...,1008.1,1007.9,2.0,194.0,4452.0,26.4,25.8,96.6,1008.1,1007.8
2,2.0,224.0,3906.0,26.4,25.6,95.2,1008.1,1008.0,1.6,229.0,...,1008.1,1008.0,1.8,184.0,4453.0,26.4,25.9,96.6,1008.1,1007.8
3,1.9,211.0,3990.0,26.4,25.7,95.1,1008.1,1008.0,1.7,236.0,...,1008.1,1007.9,1.1,194.0,4470.0,26.5,26.0,96.7,1008.1,1007.8
4,1.9,226.0,4087.0,26.5,25.7,95.2,1008.1,1007.9,1.6,239.0,...,1008.1,1007.9,0.6,210.0,4565.0,26.6,26.0,96.6,1008.1,1007.8

In [10]:
df_cls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129600 entries, 0 to 129599
Data columns (total 23 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   spdWind_10    129600 non-null  float64
 1   dirWind_10    129600 non-null  float64
 2   cd_10         129600 non-null  float64
 3   AT_10         129600 non-null  float64
 4   dp_10         129600 non-null  float64
 5   rh_10         129600 non-null  float64
 6   QNH_10        129600 non-null  float64
 7   QFE_10        129600 non-null  float64
 8   spdWind_1028  129600 non-null  float64
 9   dirWind_1028  129600 non-null  float64
 10  AT_1028       129600 non-null  float64
 11  dp_1028       129600 non-null  float64
 12  rh_1028       129600 non-null  float64
 13  QNH_1028      129600 non-null  float64
 14  QFE_1028      129600 non-null  float64
 15  spdWind_28    129600 non-null  float64
 16  dirWind_28    129600 non-null  float64
 17  cd_28         129600 non-null  float64
 18  AT_28         129600 non-null  float64
 19  dp_28         129600 non-null  float64
 20  rh_28         129600 non-null  float64
 21  QNH_28        129600 non-null  float64
 22  QFE_28        129600 non-null  float64
dtypes: float64(23)
memory usage: 22.7 MB

In [11]:
df_cls.describe()

,spdWind_10,dirWind_10,cd_10,AT_10,dp_10,rh_10,QNH_10,QFE_10,spdWind_1028,dirWind_1028,...,QNH_1028,QFE_1028,spdWind_28,dirWind_28,cd_28,AT_28,dp_28,rh_28,QNH_28,QFE_28
count,129600.000000,129600.00000,129600.000000,129600.000000,129600.000000,129600.000000,129600.000000,129600.000000,129600.000000,129600.000000,...,129600.000000,129600.000000,129600.000000,129600.000000,129600.000000,129600.000000,129600.000000,129600.000000,129600.000000,129600.000000
mean,6.153677,226.11412,2801.681177,27.180196,25.318833,90.130985,1008.025996,1007.695401,6.667092,234.393434,...,1008.043961,1007.715072,6.750649,222.987006,2352.149448,27.273330,25.411774,90.411934,1007.908413,1007.575884
std,3.625992,81.57607,3756.109368,2.544801,0.975471,11.281679,1.819930,1.816424,3.799512,83.711845,...,1.806041,1.802136,3.885902,83.536818,3059.975062,2.540817,1.211104,13.067017,1.810559,1.809653
min,0.000000,0.00000,-5.000000,22.300000,20.000000,47.000000,1002.000000,1001.700000,0.000000,0.000000,...,1002.000000,1001.700000,0.000000,0.000000,-2.000000,22.200000,18.700000,41.900000,1002.000000,1001.600000
25%,3.500000,208.00000,-4.000000,25.000000,24.700000,82.400000,1006.800000,1006.400000,3.900000,210.000000,...,1006.800000,1006.500000,3.900000,198.000000,-2.000000,25.100000,24.700000,79.900000,1006.800000,1006.300000
50%,5.400000,255.00000,114.000000,26.400000,25.200000,94.500000,1008.100000,1007.800000,5.900000,267.000000,...,1008.100000,1007.800000,6.000000,255.000000,111.000000,26.500000,25.300000,99.700000,1008.100000,1007.600000
75%,8.100000,275.00000,5739.000000,29.300000,25.900000,100.000000,1009.500000,1009.000000,8.800000,288.000000,...,1009.500000,1009.000000,8.800000,274.000000,5164.000000,29.371197,26.000000,100.000000,1009.100000,1008.900000
max,32.800000,360.00000,14911.000000,34.000000,28.800000,100.000000,1012.900000,1012.600000,30.800000,360.000000,...,1012.900000,1012.700000,31.300000,360.000000,32007.000000,34.400000,30.800000,100.000000,1012.900000,1012.600000

In [12]:
def evaluate_models(x, y, test_size=0.2, random_state=0):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=test_size, random_state=random_state)
    # Initialize models
    models = {
        'Linear Regression': LinearRegression(),
        # 'Ridge Regression': Ridge(),
        # 'Lasso Regression': Lasso(),
        'Random Forest': RandomForestRegressor(),
        # 'Support Vector Machine': SVR(),
        'Decision Tree': DecisionTreeRegressor(),
        'K-Nearest Neighbors': KNeighborsRegressor()
    }
    
    for model_name, model in models.items():
        model.fit(x_train, y_train)
        y_pred = model.predict(x_test)

        # Evaluate the model
        r2 = r2_score(y_test, y_pred)

        # Convert the R-squared score to a percentage
        percentage_score = r2 * 100

        print(f"{model_name} - Akurasi Skor: {percentage_score:.2f}%")

In [14]:
x_speedwind = df_cls[['spdWind_10', 'spdWind_28']]
y_speedwind = df_cls['spdWind_1028']

evaluate_models(x_speedwind, y_speedwind)

Linear Regression - Akurasi Skor: 87.47%
Random Forest - Akurasi Skor: 85.77%
Decision Tree - Akurasi Skor: 84.11%
K-Nearest Neighbors - Akurasi Skor: 84.95%

In [15]:
x_dynamic = df_cls[['dirWind_10', 'dirWind_28']]
y_dynamic = df_cls['dirWind_1028']

evaluate_models(x_dynamic, y_dynamic)

Linear Regression - Akurasi Skor: 71.32%
Random Forest - Akurasi Skor: 70.77%
Decision Tree - Akurasi Skor: 57.28%
K-Nearest Neighbors - Akurasi Skor: 72.51%

In [16]:
x = df_cls[['AT_10', 'AT_28']]
y = df_cls['AT_1028']

evaluate_models(x, y)

Linear Regression - Akurasi Skor: 93.46%
Random Forest - Akurasi Skor: 93.86%
Decision Tree - Akurasi Skor: 93.83%
K-Nearest Neighbors - Akurasi Skor: 92.58%

In [17]:
x = df_cls[['AT_10', 'AT_28','rh_10', 'rh_28','dp_10', 'dp_28']]
y = df_cls['AT_1028']

evaluate_models(x, y)

Linear Regression - Akurasi Skor: 93.50%
Random Forest - Akurasi Skor: 95.18%
Decision Tree - Akurasi Skor: 94.31%
K-Nearest Neighbors - Akurasi Skor: 93.83%

In [18]:
x = df_cls[['AT_10', 'AT_28','rh_10', 'rh_28','dp_10', 'dp_28','QNH_10', 'QNH_28']]
y = df_cls['AT_1028']

evaluate_models(x, y)

Linear Regression - Akurasi Skor: 93.52%
Random Forest - Akurasi Skor: 97.40%
Decision Tree - Akurasi Skor: 96.92%
K-Nearest Neighbors - Akurasi Skor: 96.99%

In [19]:
x = df_cls[['dp_10', 'dp_28']]
y = df_cls['dp_1028']
evaluate_models(x, y)

Linear Regression - Akurasi Skor: 67.62%
Random Forest - Akurasi Skor: 76.51%
Decision Tree - Akurasi Skor: 76.07%
K-Nearest Neighbors - Akurasi Skor: 72.63%

In [20]:
x = df_cls[['rh_10', 'rh_28']]
y = df_cls['rh_1028']
evaluate_models(x, y)

Linear Regression - Akurasi Skor: 89.13%
Random Forest - Akurasi Skor: 91.99%
Decision Tree - Akurasi Skor: 91.05%
K-Nearest Neighbors - Akurasi Skor: 92.00%

In [21]:
x = df_cls[['QNH_10', 'QNH_28']]
y = df_cls['QNH_1028']
evaluate_models(x, y)

Linear Regression - Akurasi Skor: 98.11%
Random Forest - Akurasi Skor: 98.19%
Decision Tree - Akurasi Skor: 98.19%
K-Nearest Neighbors - Akurasi Skor: 97.97%

In [22]:
x = df_cls[['QFE_10', 'QFE_28']]
y = df_cls['QFE_1028']
evaluate_models(x, y)

Linear Regression - Akurasi Skor: 98.12%
Random Forest - Akurasi Skor: 98.22%
Decision Tree - Akurasi Skor: 98.22%
K-Nearest Neighbors - Akurasi Skor: 97.87%